### ISSUE TITLE
ggsave doesn't save lolliplot

### ISSUE THREAD

**Issue by csmatyi** [jianhong/trackViewer.documentation#2]
Hi!

I also want to save the lolliplot in a shiny app, but it is not working for me:

  output$dl_mut_plot <- downloadHandler(
    filename = "mutation_plot.png",
    content = function(file) {ggsave(file,mutation_plotter(),device="png")}
  )

where mutation_plotter() is a reactive function that generates the lolliplot.

**Comment by jianhong** [comment]
trackViewer is using 'grid' system, not ggplot.

**Comment by csmatyi** [comment]
> trackViewer is using 'grid' system, not ggplot.

How do you save a figure in the grid system?

Thanks, Matt

**Comment by jianhong** [comment]
Try ?pdf or ?png

From: Matthew Cserhati ***@***.***>
Date: Tuesday, November 8, 2022 at 6:25 PM
To: jianhong/trackViewer.documentation ***@***.***>
Cc: JIANHONG OU ***@***.***>, Comment ***@***.***>
Subject: Re: [jianhong/trackViewer.documentation] ggsave doesn't save lolliplot (Issue #2)

trackViewer is using 'grid' system, not ggplot.

How do you save a figure in the grid system?

Thanks, Matt
